export const appLaunchErrorTypes = {
  CERTIFICATE_INSTALL_FAILED: "CERTIFICATE_INSTALL_FAILED",
  CERTUTIL_NOT_FOUND: "CERTUTIL_NOT_FOUND",
  APP_ACTIVATION_FAILED: "APP_ACTIVATION_FAILED",
  APP_DEACTIVATE_FAILED: "APP_DEACTIVATE_FAILED",
  CLOSE_CONFIRM_DENIED: "CLOSE_CONFIRM_DENIED",
  TOGGLE_SYSTEM_WIDE_PROXY_FAILED: "TOGGLE_PROXY_FAILED",
  SYSTEM_WIDE_PROXY_NOT_SUPPORTED: "SYSTEM_WIDE_PROXY_NOT_SUPPORTED",
  MISC: "MISCELLANEOUS",
}
